### ISSUE TITLE
WebService Language

### ISSUE THREAD

**Issue by ericp1337** [SergueiFedorov/RateMyPaulWebService#1]
Thank you for open sourcing the server, but why not go with PHP or something so that it can be more easily run on apache2 or nginx servers. I'm assuming you wrote it in ASP.net

**Comment by SergueiFedorov** [comment]
It's in ASP.NET MVC. The reason is because I am familiar with the Microsoft development stack. The other is that I have access to some very useful .NET libraries like the HtmlAgilityPack. Not to mention the really useful unit testing framework and most importantly LINQ.
